# Generated by Django 2.2.6 on 2019-10-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
